### ISSUE TITLE
Functionality to draw tracks

### ISSUE THREAD

**Issue by Vaarun-C** [acmpesuecc/NEAT-cars#6]
Aim to implement a paint program using Pygame that allows users to draw tracks themselves. This user-generated track will serve as the training environment for the algorithm to learn and navigate.

**Objective:**
The primary objective of this issue is to develop a user-friendly paint program within our project that empowers users to create custom tracks for the algorithm to navigate. This feature not only adds interactivity to the project but also provides a valuable tool for testing and training the algorithm on diverse track designs.

**Proposed Functionality:**
1. Develop a paint program within the Pygame interface.
2. Allow users to draw custom tracks, including defining the starting and finishing points.

**Acceptance Criteria:**
- The paint program is successfully integrated into the project.
- Users can create, and save custom tracks within the program.
- The solution does not rely on external libraries beyond PyGame.

Have fun :)

**Comment by Python-is-better-than-Java** [comment]
Can I be assigned this?

**Comment by Vaarun-C** [comment]
Sure go ahead @Python-is-better-than-Java :)

**Comment by SuchitraShankar07** [comment]
could i be assigned this?

**Comment by ssether04** [comment]
can i get assigned if this is still open?

**Comment by Prashantradder** [comment]
could i get assigned

**Comment by DedLad** [comment]
giv
